services:
  ekh:
    build: .
    container_name: ekh
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
  postgres:
    image: pgvector/pgvector:pg16-trixie
    container_name: postgres-ekh
    shm_size: 4g
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data_ekh:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-ekh
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8081:80"
    depends_on:
      - postgres
  rabbitmq:
    image: rabbitmq:4.2.1-management
    container_name: rabbitmq-ekh
    hostname: rabbitmq-ekh
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data_ekh:/var/lib/rabbitmq
      - rabbitmq_logs_ekh:/var/log/rabbitmq
volumes:
  postgres_data_ekh:
  rabbitmq_data_ekh:
  rabbitmq_logs_ekh: