{{- if kindIs "string" .Values.postgresql.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ekh.fullname" . }}-postgresql-secret
  labels: {{- include "ekh.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}
{{- end }}
