{{- if and (kindIs "string" .Values.rabbitmq.url) (ne .Values.rabbitmq.url "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ekh.fullname" . }}-rabbitmq-url-secret
  labels: {{- include "ekh.labels" . | nindent 4 }}
type: Opaque
data:
  RABBITMQ_URL: {{ .Values.rabbitmq.url | b64enc | quote }}
{{- end }}