apiVersion: v1
kind: Service
metadata:
  name: {{ include "ekh.fullname" . }}
  labels:
    app.kubernetes.io/name: ekh
    app.kubernetes.io/instance: ekh-abcxyz
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: ekh
    app.kubernetes.io/managed-by: Helm

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ekh.selectorLabels" . | nindent 4 }}
